config/routes.rb
Music::Application.routes.draw do

  get "genres/index"
  get "welcome/index"
 
  resources :songs do
    member do
      get 'download'
    end
  end

  resources :welcome do
    collection do
      get 'json'
    end
  end
  
  resources :genres

  resources :locations
  root 'welcome#index'

   

  

end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :songs, :dependent => :destroy
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_attached_file :song
	belongs_to :genre, :foreign_key => :genre_id

 def self.search(query)
	where("title like ?", "%#{query}%")
 end

 def self.sear(data, page)
  	paginate :per_page => 2, :page => page,
           :conditions => ['title like ?', "%#{data}%"],
           :order => 'title'
 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
  end

  def new
  end

  def create
    @genre = Genre.new(params[:genre].permit(:name))
    @genre.save
    redirect_to @genre
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
      if params[:search].present?
    @locations = Location.near(params[:search], 50, :order => :distance)
  else
    @locations = Location.all
  end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    #params.require(:product).permit(:title, :description, :image_url, :price)
    #@location = Location.new(params[:location])
    @location = Location.new(params.require(:location).permit(:address, :longitude, :latitude))
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params.require(:location).permit(:address, :longitude, :latitude))
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url, :notice => "Successfully destroyed location."
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def index
		@songs = Song.all
		
		if params[:search]
		  @songs = Song.search(params[:search]).order("created_at DESC")
		else
		  @songs = Song.order("created_at DESC")
		end

		 @songs = Song.sear(params[:data], params[:page])
		 
	end

	def new

	end

	def create
      @song = Song.new(params[:song].permit(:title, :description, :duration, :genre_id, :song))
	  @song.save
  	  redirect_to @song
	end

	def show
		@song = Song.find(params[:id])	
	end

	def download
		@download = Song.find(params[:id])
		send_file @download.song.path,
            :filename => @download.song_file_name,
            :type => @download.song_content_type,
            :disposition => 'attachment'
		flash[:notice] = "Your file has been downloaded"
    end

	private

  	def song_params
    	params.require(:song).permit(:title, :description, :duration)
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def json
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/genres/index.html.haml
%h1 Genres#index
%p Find me in app/views/genres/index.html.haml

app/views/genres/new.html.haml
%center
 %h2 Add a new Genre
 %hr
=form_for :genre,  url: genres_path do |f|
 %center
  %table
   %tr
    %td{ :style => "text-align: center;" }
     =f.label :name
   %tr
    %td
     =f.text_field :name
   %tr
    %td{ :style => "text-align: center;" } 
     =f.submit "Submit"

app/views/genres/show.html.haml
%h3 The Genre you have just added is :
.genre_name
 %strong Genre Name:
 =@genre.name

app/views/layouts/application.html.haml
!!! 5
%html
 %head
  %title Music
  %script{:src => "http://maps.google.com/maps/api/js?sensor=false"}
  =stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  =javascript_include_tag "application", "data-turbolinks-track" => true
  =csrf_meta_tags
 %body
  .navbar.navbar-fixed-top
   .navbar-inner.my-navbar
    .container
     %ul.nav.my-nav
      %li.active
       %a.brand Music Is My Medicine
      %li
       %a{ :href => "#"} About
      %li
       %a{ :href => "#"} Portfolio
      %li
       %a{ :href => "#"} Contact
     =form_tag(songs_path, :method => "get", class: "navbar-form", id: "search-form") do
      .input-append
       =text_field_tag :search, params[:search], class: "span2", placeholder: "Search for Songs"
       %button Search
   =yield

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<h1>Locations</h1>
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
<% end %>
<center>
<div class="mid">
<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
</div>
</center>
<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<h1>Location</h1>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>



<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>



<h3>Nearby Locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/songs/index.html.haml
%center
 %h2 List of Songs
%a#anchor1.anchorLink{href: "#myAnchor", rel: ""} Link to the anchor
=link_to "Upload New Songs", new_song_path
-@songs.each do |song|
 %center
  %h4{ :style => "text-decoration: underline;" }
   =song.title
  %strong Name: 
  =song.song_file_name
  %br
  %strong Description:
  =song.description
  %br
  %strong Size:
  =song.song_file_size
  %br
  %strong Duration:
  =song.duration
  %br
  %strong Genre:
  =song.genre.present? ? song.genre.name : 'N/A'
  %br
  =link_to "Download", download_song_path(song)
  %hr
%center
 =will_paginate @songs

app/views/songs/new.html.haml
=form_for :song,  url: songs_path do |f|
 %br
 %center
  %table.details
   %tr
    %td
     =f.label :title
    %td.right
     =f.text_field :title
   %tr
    %td
     =f.label :description
    %td.right
     =f.text_area :description
   %tr
    %td
     =f.label :duration
    %td.right
     =f.text_field :duration
     mins
   %tr
    %td
     =f.label :genre
    %td.right
     =f.collection_select :genre_id, Genre.all, :id, :name, multiple: true, :prompt => "Please Select a Genre"
   %tr
    %td
     =f.label :song, "Upload File"
    %td.right
     =f.file_field :song
   %tr
    %td.upload_btn
     =f.submit "Upload"

app/views/songs/show.html.erb
<h2>The details of the song you just uploaded is</h2>
<h2>show.html</h2>
<p>
<strong>Title:</strong>
<%= @song.title %>
</p>

<p>
<strong>Description:</strong>
<%= @song.description %>
</p>

<p>
<strong>Size:</strong>
<%= @song.song_file_size %> bytes
</p>

<p>
<strong>Duration:</strong>
<%= @song.duration %> min
</p>

<p>
<strong>File Name:</strong>
<%= @song.song_file_name %>
</p>

app/views/welcome/index.html.erb
<!-- Charts div start -->
<table width="80%">
  <tr>
    <td width="40%"><div id="fruits_bar_chart" style="width: 560px; height: 300px;"></div></td>
    <td width="40%"><div id="fruits_pie_chart" style="width: 560px; height: 300px;"></div></td>
  </tr>
  <tr>
    <td width="50%"><div id="fruits_line_chart" style="width: 560px; height: 300px;"></div></td>
    <td width="50%"><div id="fruits_area_chart" style="width: 560px; height: 300px;"></div></td>
  </tr>
  <tr>
    <td width="50%"><div id="fruits_column_chart" style="width: 560px; height: 300px;"></div></td>
    <td width="50"><div id="fruits_polar_chart" style="width: 560px; height: 300px;"></div></td>
  </tr>
  <tr>
    <td width="50%"><div id="fruits_gauges_chart" style="width: 560px; height: 300px;"></div></td>
    <td width="50"><div id="fruits_clock_chart" style="width: 560px; height: 300px;"></div></td>
  </tr>
  <tr>
    <td width="50%"><div id="fruits_range_chart" style="width: 560px; height: 300px;"></div></td>
    <td width="50"><div id="fruits_funnel_chart" style="width: 560px; height: 300px;"></div></td>
  </tr>
   
</table>
<!-- Charts div end -->

<table class="pretty">
  <!-- Orders table code here -->
</table>